name: Trigger Update README Workflow

on:
  workflow_dispatch:
    inputs:
      table:
        type: choice
        description: 'Name of the table being updated'
        required: true
        default: 'memgraph'
        options:
          - 'memgraph'
          - 'mage'
      limit:
        type: integer
        description: 'Maximum number of daily builds to keep'
        required: true
        default: 42
      data:
        type: string
        description: 'JSON string with data for updating the README'
        required: true
        default: '{}'

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger target workflow via API
        env:
          # Use a token with repo dispatch permission
          GITHUB_TOKEN: ${{ secrets.TEST_PAGE_PAT }}
          TABLE: ${{ github.event.inputs.table }}
          LIMIT: ${{ github.event.inputs.limit }}
          DATA: ${{ github.event.inputs.data }}
        run: |
          # Build the JSON payload using jq
          payload=$(jq -n \
            --arg table "$TABLE" \
            --arg limit "$LIMIT" \
            --arg build_data "$DATA" \
            '{
                event_type: "trigger_update_readme",
                client_payload: {
                  table: $table,
                  limit: $limit,
                  build_data: $build_data
                }
              }')
          echo "Payload: $payload"
          # Send the dispatch request
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/mattkjames7/test-page/dispatches \
            -d "$payload"